version: "3.8"
services:
  transporter:
    build: ./sql_to_pg/
    env_file:
    - webvars_example.env
    depends_on:
      - db
  db:
    build: ./database/
    env_file:
    - dbvars_example.env
    volumes:
      - database_data:/var/lib/postgresql/data
  # etl:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
    expose:
      - "9200"

volumes:
  database_data: